---
# Source: gbchn/templates/slavedeployable.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: gbchn-gbchn-redisslave
  namespace: gbchn
  annotations:
    app.ibm.com/is-local-deployable: "true"
  labels:
    app: gbchn
    chart: gbchn-0.1.0
    release: gbchn
    heritage: Tiller
    component: main
    package: guestbook
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: gbchn-gbchn-redisslave
    spec:
      selector:
        matchLabels:
          app: gbchn
          release: gbchn
          role: slave
          tier: backend
      replicas: 1
      template:
        metadata:
          labels:
            app: gbchn
            release: gbchn
            role: slave
            tier: backend
        spec:
          containers:
          - name: gbchn
            image: "gcr.io/google_samples/gb-redisslave:v3"
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 6379
            securityContext:
              runAsUser: 0
            env:
            - name: GET_HOSTS_FROM
              value: dns
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: gbchn-gbchn-redisslaveservice
  namespace: gbchn
  annotations:
    app.ibm.com/is-local-deployable: "true"
  labels:
    app: gbchn
    chart: gbchn-0.1.0
    release: gbchn
    heritage: Tiller
    component: main
    package: guestbook
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: redis-slave
    spec:
      type: ClusterIP
      ports:
        - port: 6379
      selector:
        app: gbchn
        release: gbchn
        role: slave
        tier: backend
