---
# Source: gbapp/templates/application.yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gbapp-gbapp
  namespace: gbapp
  labels:
    app: gbapp
    chart: gbapp-0.1.0
    release: gbapp
    heritage: Tiller
spec:
  selector:
    matchExpressions:
    - key: release
      operator: In
      values:
      - gbapp
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
