apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: simple-app
  namespace: saapp
  labels:
    app: simple-app
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - simple-app
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
