apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: simple-app
  namespace: saapp
  labels:
    app: simple-app
spec:
  channel: sachannel/simple-app
  placement:
    placementRef:
      name: simple-app
      kind: PlacementRule
      group: app.ibm.com
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: simple-app
